<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname(dirname($vendorDir));

return array(
    'Psr\\Log\\' => array($vendorDir . '/psr/log/Psr/Log'),
    'Peterujah\\NanoBlock\\' => array($vendorDir . '/peterujah/cache/src'),
    'Luminova\\Template\\' => array($baseDir . '/system/Template'),
    'Luminova\\Sessions\\' => array($baseDir . '/system/Sessions'),
    'Luminova\\Seo\\' => array($baseDir . '/system/Seo'),
    'Luminova\\Security\\' => array($baseDir . '/system/Security'),
    'Luminova\\Router\\' => array($baseDir . '/system/Router'),
    'Luminova\\Logger\\' => array($baseDir . '/system/Logger'),
    'Luminova\\Functions\\' => array($baseDir . '/system/Functions'),
    'Luminova\\Exceptions\\' => array($baseDir . '/system/Exceptions'),
    'Luminova\\Database\\' => array($baseDir . '/system/Database'),
    'Luminova\\Config\\' => array($baseDir . '/system/Config'),
    'Luminova\\Composer\\' => array($baseDir . '/system/Composer'),
    'Luminova\\Command\\' => array($baseDir . '/system/Command'),
    'Luminova\\Cache\\' => array($baseDir . '/system/Cache'),
    'Luminova\\Arrays\\' => array($baseDir . '/system/Arrays'),
    'Luminova\\' => array($baseDir . '/system'),
    'App\\Controllers\\' => array($baseDir . '/app/Controllers'),
);
