<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit9c155849e043191fc1df7e0b46712cd7
{
    public static $prefixLengthsPsr4 = array (
        'P' => 
        array (
            'Psr\\Log\\' => 8,
            'Peterujah\\NanoBlock\\' => 20,
        ),
        'L' => 
        array (
            'Luminova\\Template\\' => 18,
            'Luminova\\Sessions\\' => 18,
            'Luminova\\Seo\\' => 13,
            'Luminova\\Security\\' => 18,
            'Luminova\\Router\\' => 16,
            'Luminova\\Logger\\' => 16,
            'Luminova\\Functions\\' => 19,
            'Luminova\\Exceptions\\' => 20,
            'Luminova\\Database\\' => 18,
            'Luminova\\Config\\' => 16,
            'Luminova\\Composer\\' => 18,
            'Luminova\\Command\\' => 17,
            'Luminova\\Cache\\' => 15,
            'Luminova\\Arrays\\' => 16,
            'Luminova\\' => 9,
        ),
        'A' => 
        array (
            'App\\Controllers\\' => 16,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Psr\\Log\\' => 
        array (
            0 => __DIR__ . '/..' . '/psr/log/Psr/Log',
        ),
        'Peterujah\\NanoBlock\\' => 
        array (
            0 => __DIR__ . '/..' . '/peterujah/cache/src',
        ),
        'Luminova\\Template\\' => 
        array (
            0 => __DIR__ . '/../../..' . '/system/Template',
        ),
        'Luminova\\Sessions\\' => 
        array (
            0 => __DIR__ . '/../../..' . '/system/Sessions',
        ),
        'Luminova\\Seo\\' => 
        array (
            0 => __DIR__ . '/../../..' . '/system/Seo',
        ),
        'Luminova\\Security\\' => 
        array (
            0 => __DIR__ . '/../../..' . '/system/Security',
        ),
        'Luminova\\Router\\' => 
        array (
            0 => __DIR__ . '/../../..' . '/system/Router',
        ),
        'Luminova\\Logger\\' => 
        array (
            0 => __DIR__ . '/../../..' . '/system/Logger',
        ),
        'Luminova\\Functions\\' => 
        array (
            0 => __DIR__ . '/../../..' . '/system/Functions',
        ),
        'Luminova\\Exceptions\\' => 
        array (
            0 => __DIR__ . '/../../..' . '/system/Exceptions',
        ),
        'Luminova\\Database\\' => 
        array (
            0 => __DIR__ . '/../../..' . '/system/Database',
        ),
        'Luminova\\Config\\' => 
        array (
            0 => __DIR__ . '/../../..' . '/system/Config',
        ),
        'Luminova\\Composer\\' => 
        array (
            0 => __DIR__ . '/../../..' . '/system/Composer',
        ),
        'Luminova\\Command\\' => 
        array (
            0 => __DIR__ . '/../../..' . '/system/Command',
        ),
        'Luminova\\Cache\\' => 
        array (
            0 => __DIR__ . '/../../..' . '/system/Cache',
        ),
        'Luminova\\Arrays\\' => 
        array (
            0 => __DIR__ . '/../../..' . '/system/Arrays',
        ),
        'Luminova\\' => 
        array (
            0 => __DIR__ . '/../../..' . '/system',
        ),
        'App\\Controllers\\' => 
        array (
            0 => __DIR__ . '/../../..' . '/app/Controllers',
        ),
    );

    public static $classMap = array (
        'App\\Controllers\\Application' => __DIR__ . '/../../..' . '/app/Controllers/Application.php',
        'App\\Controllers\\Config' => __DIR__ . '/../../..' . '/app/Controllers/Config.php',
        'App\\Controllers\\Func' => __DIR__ . '/../../..' . '/app/Controllers/Func.php',
        'App\\Controllers\\HelloWorld' => __DIR__ . '/../../..' . '/app/Controllers/HelloWorld.php',
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
        'Luminova\\Arrays\\ArrayInput' => __DIR__ . '/../../..' . '/system/Arrays/ArrayInput.php',
        'Luminova\\BaseController' => __DIR__ . '/../../..' . '/system/BaseController.php',
        'Luminova\\Cache\\Compress' => __DIR__ . '/../../..' . '/system/Cache/Compress.php',
        'Luminova\\Cache\\FileCache' => __DIR__ . '/../../..' . '/system/Cache/FileCache.php',
        'Luminova\\Cache\\Optimizer' => __DIR__ . '/../../..' . '/system/Cache/Optimizer.php',
        'Luminova\\Command\\AppCommand' => __DIR__ . '/../../..' . '/system/Command/AppCommand.php',
        'Luminova\\Command\\Create' => __DIR__ . '/../../..' . '/system/Command/Create.php',
        'Luminova\\Command\\Plugin' => __DIR__ . '/../../..' . '/system/Command/Plugin.php',
        'Luminova\\Command\\RebuildCommand' => __DIR__ . '/../../..' . '/system/Command/RebuildCommand.php',
        'Luminova\\Command\\Subscriber' => __DIR__ . '/../../..' . '/system/Command/Subscriber.php',
        'Luminova\\Composer\\BaseComposer' => __DIR__ . '/../../..' . '/system/Composer/BaseComposer.php',
        'Luminova\\Composer\\Builder' => __DIR__ . '/../../..' . '/system/Composer/Builder.php',
        'Luminova\\Composer\\Updater' => __DIR__ . '/../../..' . '/system/Composer/Updater.php',
        'Luminova\\Config\\BaseConfig' => __DIR__ . '/../../..' . '/system/Config/BaseConfig.php',
        'Luminova\\Config\\DotEnv' => __DIR__ . '/../../..' . '/system/Config/DotEnv.php',
        'Luminova\\Config\\PHPStanRules' => __DIR__ . '/../../..' . '/system/Config/PHPStanRules.php',
        'Luminova\\Database\\Columns' => __DIR__ . '/../../..' . '/system/Database/Columns.php',
        'Luminova\\Database\\Conn' => __DIR__ . '/../../..' . '/system/Database/Conn.php',
        'Luminova\\Database\\Mysqli' => __DIR__ . '/../../..' . '/system/Database/Mysqli.php',
        'Luminova\\Database\\Pdo' => __DIR__ . '/../../..' . '/system/Database/Pdo.php',
        'Luminova\\Database\\Query' => __DIR__ . '/../../..' . '/system/Database/Query.php',
        'Luminova\\Exceptions\\ClassNotFoundException' => __DIR__ . '/../../..' . '/system/Exceptions/ClassNotFoundException.php',
        'Luminova\\Exceptions\\DatabaseException' => __DIR__ . '/../../..' . '/system/Exceptions/DatabaseException.php',
        'Luminova\\Exceptions\\FileNotFoundException' => __DIR__ . '/../../..' . '/system/Exceptions/FileNotFoundException.php',
        'Luminova\\Exceptions\\InvalidArgumentException' => __DIR__ . '/../../..' . '/system/Exceptions/InvalidArgumentException.php',
        'Luminova\\Exceptions\\PageNotFoundException' => __DIR__ . '/../../..' . '/system/Exceptions/PageNotFoundException.php',
        'Luminova\\Functions\\FunctionInterface' => __DIR__ . '/../../..' . '/system/Functions/FunctionInterface.php',
        'Luminova\\Functions\\Functions' => __DIR__ . '/../../..' . '/system/Functions/Functions.php',
        'Luminova\\Logger\\FileLogger' => __DIR__ . '/../../..' . '/system/Logger/FileLogger.php',
        'Luminova\\Logger\\LoggerInterface' => __DIR__ . '/../../..' . '/system/Logger/LoggerInterface.php',
        'Luminova\\Router\\BaseRouter' => __DIR__ . '/../../..' . '/system/Router/BaseRouter.php',
        'Luminova\\Router\\Router' => __DIR__ . '/../../..' . '/system/Router/Router.php',
        'Luminova\\Security\\Csrf' => __DIR__ . '/../../..' . '/system/Security/Csrf.php',
        'Luminova\\Seo\\Meta' => __DIR__ . '/../../..' . '/system/Seo/Meta.php',
        'Luminova\\Sessions\\Session' => __DIR__ . '/../../..' . '/system/Sessions/Session.php',
        'Luminova\\Template\\Template' => __DIR__ . '/../../..' . '/system/Template/Template.php',
        'Peterujah\\NanoBlock\\Cache' => __DIR__ . '/..' . '/peterujah/cache/src/Cache.php',
        'Psr\\Log\\AbstractLogger' => __DIR__ . '/..' . '/psr/log/Psr/Log/AbstractLogger.php',
        'Psr\\Log\\InvalidArgumentException' => __DIR__ . '/..' . '/psr/log/Psr/Log/InvalidArgumentException.php',
        'Psr\\Log\\LogLevel' => __DIR__ . '/..' . '/psr/log/Psr/Log/LogLevel.php',
        'Psr\\Log\\LoggerAwareInterface' => __DIR__ . '/..' . '/psr/log/Psr/Log/LoggerAwareInterface.php',
        'Psr\\Log\\LoggerAwareTrait' => __DIR__ . '/..' . '/psr/log/Psr/Log/LoggerAwareTrait.php',
        'Psr\\Log\\LoggerInterface' => __DIR__ . '/..' . '/psr/log/Psr/Log/LoggerInterface.php',
        'Psr\\Log\\LoggerTrait' => __DIR__ . '/..' . '/psr/log/Psr/Log/LoggerTrait.php',
        'Psr\\Log\\NullLogger' => __DIR__ . '/..' . '/psr/log/Psr/Log/NullLogger.php',
        'Psr\\Log\\Test\\DummyTest' => __DIR__ . '/..' . '/psr/log/Psr/Log/Test/DummyTest.php',
        'Psr\\Log\\Test\\LoggerInterfaceTest' => __DIR__ . '/..' . '/psr/log/Psr/Log/Test/LoggerInterfaceTest.php',
        'Psr\\Log\\Test\\TestLogger' => __DIR__ . '/..' . '/psr/log/Psr/Log/Test/TestLogger.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit9c155849e043191fc1df7e0b46712cd7::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit9c155849e043191fc1df7e0b46712cd7::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit9c155849e043191fc1df7e0b46712cd7::$classMap;

        }, null, ClassLoader::class);
    }
}
