#!/usr/bin/env php
<?php
/**
 * Luminova Framework
 *
 * @package Luminova
 * @author Ujah Chigozie Peter
 * @copyright (c) Nanoblock Technology Ltd
 * @license See LICENSE file
 */

// Refuse to run when called from php-cgi
if (strpos(PHP_SAPI, 'cgi') === 0) {
    exit("The cli tool is not supported when running php-cgi. It needs php-cli to function!\n\n");
}

// We want errors to be shown when using it from the CLI.
error_reporting(-1);
ini_set('display_errors', '1');

// Location of the framework bootstrap file.
require __DIR__ . '/bootstrap/autoload.php';

// Ensure the current directory is pointing to the front controller's directory
chdir(FRONT_CONTROLLER);


// Load environment settings from .env files into $_SERVER and $_ENV
Luminova\Config\DotEnv::register(__DIR__ . DIRECTORY_SEPARATOR . '.env');

// Load our paths config file
$paths = new Luminova\Config\SystemPaths();

// Define ENVIRONMENT
if (!defined('ENVIRONMENT')) {
    define('ENVIRONMENT', getenv('app.environment.mood', 'production'));
}

// Show basic information before we do anything else.
if (($suppress = array_search('--no-header', $_SERVER['argv'], true) !== false)) {
    unset($_SERVER['argv'][$suppress]);
    $suppress = true;
}

// Initialize our Console
$console = new  Luminova\Command\Console($suppress);

// Initialize Terminal CLI
$terminal = $console::getTerminal();

// Run our console instance
$console->run($terminal);