<?php 
/**
 * GeoNameSearch - Php Geoname search wrapper, to help reduce too much api call
 * @author      Peter Chigozie(NG) peterujah
 * @copyright   Copyright (c), 2021 Peter(NG) peterujah
 * @license     MIT public license
 */
return array(
		"AD" => array("currency" => "EUR","currency_symbol" => "&#8364;","name" => "ANDORRA","short_name" => "AD","code" => "+376"),
		"AE" => array("currency" => "AED","currency_symbol" => "&#1583;.&#1573;","name" => "UNITED ARAB EMIRATES","short_name" => "AE","code" => "+971"),
		"AF" => array("currency" => "AFN","currency_symbol" => "&#65;&#102;","name" => "AFGHANISTAN","short_name" => "AF","code" => "+93"),
		"AG" => array("currency" => "XCD","currency_symbol" => "&#36;","name" => "ANTIGUA AND BARBUDA","short_name" => "AG","code" => "+1268"),
		"AI" => array("currency" => "XCD","currency_symbol" => "&#36;","name" => "ANGUILLA","short_name" => "AI","code" => "+1264"),
		"AL" => array("currency" => "ALL","currency_symbol" => "&#76;&#101;&#107;","name" => "ALBANIA","short_name" => "AL","code" => "+355"),
		"AM" => array("currency" => "AMD","currency_symbol" => "&#1423;","name" => "ARMENIA","short_name" => "AM","code" => "+374"),
		"AN" => array("currency" => "ANG","currency_symbol" => "&#402;","name" => "NETHERLANDS ANTILLES","short_name" => "AN","code" => "+599"),
		"AO" => array("currency" => "AOA","currency_symbol" => "&#75;&#122;","name" => "ANGOLA","short_name" => "AO","code" => "+244"),
		"AQ" => array("currency" => "XCD","currency_symbol" => "&#36;","name" => "ANTARCTICA","short_name" => "AQ","code" => "+672"),
		"AR" => array("currency" => "ARS","currency_symbol" => "&#36;","name" => "ARGENTINA","short_name" => "AR","code" => "+54"),
		"AS" => array("currency" => "USD","currency_symbol" => "&#36;","name" => "AMERICAN SAMOA","short_name" => "AS","code" => "+1684"),
		"AT" => array("currency" => "EUR","currency_symbol" => "&#8364;","name" => "AUSTRIA","short_name" => "AT","code" => "+43"),
		"AU" => array("currency" => "AUD","currency_symbol" => "&#36;","name" => "AUSTRALIA","short_name" => "AU","code" => "+61"),
		"AW" => array("currency" => "AWG","currency_symbol" => "&#402;","name" => "ARUBA","short_name" => "AW","code" => "+297"),
		"AZ" => array("currency" => "AZN","currency_symbol" => "&#1084;&#1072;&#1085;","name" => "AZERBAIJAN","short_name" => "AZ","code" => "+994"),
		"BA" => array("currency" => "BAM","currency_symbol" => "&#75;&#77;","name" => "BOSNIA AND HERZEGOVINA","short_name" => "BA","code" => "+387"),
		"BB" => array("currency" => "BBD","currency_symbol" => "&#36;","name" => "BARBADOS","short_name" => "BB","code" => "+1246"),
		"BD" => array("currency" => "BDT","currency_symbol" => "&#2547;","name" => "BANGLADESH","short_name" => "BD","code" => "+880"),
		"BE" => array("currency" => "EUR","currency_symbol" => "&#8364;","name" => "BELGIUM","short_name" => "BE","code" => "+32"),
		"BF" => array("currency" => "XOF","currency_symbol" => "CFA","name" => "BURKINA FASO","short_name" => "BF","code" => "+226"),
		"BG" => array("currency" => "BGN","currency_symbol" => "&#1083;&#1074;","name" => "BULGARIA","short_name" => "BG","code" => "+359"),
		"BH" => array("currency" => "BHD","currency_symbol" => ".&#1583;.&#1576;","name" => "BAHRAIN","short_name" => "BH","code" => "+973"),
		"BI" => array("currency" => "BIF","currency_symbol" => "&#70;&#66;&#117;","name" => "BURUNDI","short_name" => "BI","code" => "+257"),
		"BJ" => array("currency" => "XOF","currency_symbol" => "CFA","name" => "BENIN","short_name" => "BJ","code" => "+229"),
		"BL" => array("currency" => "","currency_symbol" => "","name" => "SAINT BARTHELEMY","short_name" => "BL","code" => "+590"),
		"BM" => array("currency" => "BMD","currency_symbol" => "&#36;","name" => "BERMUDA","short_name" => "BM","code" => "+1441"),
		"BN" => array("currency" => "BND","currency_symbol" => "&#36;","name" => "BRUNEI DARUSSALAM","short_name" => "BN","code" => "+673"),
		"BO" => array("currency" => "BOB","currency_symbol" => "&#36;&#98;","name" => "BOLIVIA","short_name" => "BO","code" => "+591"),
		"BR" => array("currency" => "BRL","currency_symbol" => "&#82;&#36;","name" => "BRAZIL","short_name" => "BR","code" => "+55"),
		"BS" => array("currency" => "BSD","currency_symbol" => "&#36;","name" => "BAHAMAS","short_name" => "BS","code" => "+1242"),
		"BT" => array("currency" => "BTN","currency_symbol" => "&#78;&#117;&#46;","name" => "BHUTAN","short_name" => "BT","code" => "+975"),
		"BW" => array("currency" => "BWP","currency_symbol" => "&#80;","name" => "BOTSWANA","short_name" => "BW","code" => "+267"),
		"BY" => array("currency" => "BYR","currency_symbol" => "&#112;&#46;","name" => "BELARUS","short_name" => "BY","code" => "+375"),
		"BZ" => array("currency" => "BZD","currency_symbol" => "&#66;&#90;&#36;","name" => "BELIZE","short_name" => "BZ","code" => "+501"),
		"CA" => array("currency" => "CAD","currency_symbol" => "&#36;","name" => "CANADA","short_name" => "CA","code" => "+1"),
		"CC" => array("currency" => "AUD","currency_symbol" => "&#36;","name" => "COCOS","short_name" => "CC","code" => "+61"),
		"CD" => array("currency" => "CDF","currency_symbol" => "&#70;&#67;","name" => "CONGO DEMOCRATIC REPUBLIC","short_name" => "CD","code" => "+243"),
		"CF" => array("currency" => "XAF","currency_symbol" => "&#70;&#67;&#70;&#65;","name" => "CENTRAL AFRICAN REPUBLIC","short_name" => "CF","code" => "+236"),
		"CG" => array("currency" => "XAF","currency_symbol" => "&#70;&#67;&#70;&#65;","name" => "CONGO","short_name" => "CG","code" => "+242"),
		"CH" => array("currency" => "CHF","currency_symbol" => "&#67;&#72;&#70;","name" => "SWITZERLAND","short_name" => "CH","code" => "+41"),
		"CI" => array("currency" => "XOF","currency_symbol" => "CFA","name" => "COTE D'IVOIR","short_name" => "CI","code" => "+225"),
		"CK" => array("currency" => "NZD","currency_symbol" => "&#36;","name" => "COOK ISLANDS","short_name" => "CK","code" => "+682"),
		"CL" => array("currency" => "CLP","currency_symbol" => "&#36;","name" => "CHILE","short_name" => "CL","code" => "+56"),
		"CM" => array("currency" => "XAF","currency_symbol" => "&#70;&#67;&#70;&#65;","name" => "CAMEROON","short_name" => "CM","code" => "+237"),
		"CN" => array("currency" => "CNY","currency_symbol" => "&#165;","name" => "CHINA","short_name" => "CN","code" => "+86"),
		"CO" => array("currency" => "COP","currency_symbol" => "&#36;","name" => "COLOMBIA","short_name" => "CO","code" => "+57"),
		"CR" => array("currency" => "CRC","currency_symbol" => "&#8353;","name" => "COSTA RICA","short_name" => "CR","code" => "+506"),
		"CU" => array("currency" => "CUP","currency_symbol" => "&#8396;","name" => "CUBA","short_name" => "CU","code" => "+53"),
		"CV" => array("currency" => "CVE","currency_symbol" => "&#36;","name" => "CAPE VERDE","short_name" => "CV","code" => "+238"),
		"CX" => array("currency" => "AUD","currency_symbol" => "&#36;","name" => "CHRISTMAS ISLAND","short_name" => "CX","code" => "+61"),
		"CY" => array("currency" => "EUR","currency_symbol" => "&#8364;","name" => "CYPRUS","short_name" => "CY","code" => "+357"),
		"CZ" => array("currency" => "CZK","currency_symbol" => "&#75;&#269;","name" => "CZECH REPUBLIC","short_name" => "CZ","code" => "+420"),
		"DE" => array("currency" => "EUR","currency_symbol" => "&#8364;","name" => "GERMANY","short_name" => "DE","code" => "+49"),
		"DJ" => array("currency" => "DJF","currency_symbol" => "&#70;&#100;&#106;","name" => "DJIBOUTI","short_name" => "DJ","code" => "+253"),
		"DK" => array("currency" => "DKK","currency_symbol" => "&#107;&#114;","name" => "DENMARK","short_name" => "DK","code" => "+45"),
		"DM" => array("currency" => "XCD","currency_symbol" => "&#36;","name" => "DOMINICA","short_name" => "DM","code" => "+1767"),
		"DO" => array("currency" => "DOP","currency_symbol" => "&#82;&#68;&#36;","name" => "DOMINICAN REPUBLIC","short_name" => "DO","code" => "+1809"),
		"DZ" => array("currency" => "DZD","currency_symbol" => "&#1583;&#1580;","name" => "ALGERIA","short_name" => "DZ","code" => "+213"),
		"EC" => array("currency" => "USD","currency_symbol" => "&#36;","name" => "ECUADOR","short_name" => "EC","code" => "+593"),
		"EE" => array("currency" => "EUR","currency_symbol" => "&#8364;","name" => "ESTONIA","short_name" => "EE","code" => "+372"),
		"EG" => array("currency" => "EGP","currency_symbol" => "&#163;","name" => "EGYPT","short_name" => "EG","code" => "+20"),
		"ER" => array("currency" => "ETB","currency_symbol" => "Nkf","name" => "ERITREA","short_name" => "ER","code" => "+291"),
		"ES" => array("currency" => "EUR","currency_symbol" => "&#8364;","name" => "SPAIN","short_name" => "ES","code" => "+34"),
		"ET" => array("currency" => "ETB","currency_symbol" => "&#66;&#114;","name" => "ETHIOPIA","short_name" => "ET","code" => "+251"),
		"FI" => array("currency" => "EUR","currency_symbol" => "&#8364;","name" => "FINLAND","short_name" => "FI","code" => "+358"),
		"FJ" => array("currency" => "FJD","currency_symbol" => "&#36;","name" => "FIJI","short_name" => "FJ","code" => "+679"),
		"FK" => array("currency" => "FKP","currency_symbol" => "&#163;","name" => "MALVINAS","short_name" => "FK","code" => "+500"),
		"FM" => array("currency" => "USD","currency_symbol" => "&#36;","name" => "MICRONESIA","short_name" => "FM","code" => "+691"),
		"FO" => array("currency" => "DKK","currency_symbol" => "&#107;&#114;","name" => "FAROE ISLANDS","short_name" => "FO","code" => "+298"),
		"FR" => array("currency" => "EUR","currency_symbol" => "&#8364;","name" => "FRANCE","short_name" => "FR","code" => "+33"),
		"GA" => array("currency" => "XAF","currency_symbol" => "&#70;&#67;&#70;&#65;","name" => "GABON","short_name" => "GA","code" => "+241"),
		"GB" => array("currency" => "GBP","currency_symbol" => "&#163;","name" => "UNITED KINGDOM","short_name" => "GB","code" => "+44"),
		"GD" => array("currency" => "XCD","currency_symbol" => "&#36;","name" => "GRENADA","short_name" => "GD","code" => "+1473"),
		"GE" => array("currency" => "GEL","currency_symbol" => "&#4314;","name" => "GEORGIA","short_name" => "GE","code" => "+995"),
		"GH" => array("currency" => "GHS","currency_symbol" => "&#162;","name" => "GHANA","short_name" => "GH","code" => "+233"),
		"GI" => array("currency" => "GIP","currency_symbol" => "&#163;","name" => "GIBRALTAR","short_name" => "GI","code" => "+350"),
		"GL" => array("currency" => "DKK","currency_symbol" => "&#107;&#114;","name" => "GREENLAND","short_name" => "GL","code" => "+299"),
		"GM" => array("currency" => "GMD","currency_symbol" => "&#68;","name" => "GAMBIA","short_name" => "GM","code" => "+220"),
		"PG" => array("currency" => "PGK","currency_symbol" => "&#75;","name" => "PAPUA NEW GUINEA","short_name" => "PG","code" => "+675"),
		"GN" => array("currency" => "GNF","currency_symbol" => "&#70;&#71;","name" => "GUINEA","short_name" => "GN","code" => "+224"),
		"GQ" => array("currency" => "XAF","currency_symbol" => "&#70;&#67;&#70;&#65;","name" => "EQUATORIAL GUINEA","short_name" => "GQ","code" => "+240"),
		"GW" => array("currency" => "GWP","currency_symbol" => "GWP ","name" => "GUINEA-BISSAU","short_name" => "GW","code" => "+245"),
		"GR" => array("currency" => "EUR","currency_symbol" => "&#8364;","name" => "GREECE","short_name" => "GR","code" => "+30"),
		"GT" => array("currency" => "QTQ","currency_symbol" => " &#81;","name" => "GUATEMALA","short_name" => "GT","code" => "+502"),
		"GU" => array("currency" => "USD","currency_symbol" => "&#36;","name" => "GUAM","short_name" => "GU","code" => "+1671"),
		"GY" => array("currency" => "GYD","currency_symbol" => "&#36;","name" => "GUYANA","short_name" => "GY","code" => "+592"),
		"HK" => array("currency" => "HKD","currency_symbol" => "&#36;","name" => "HONG KONG","short_name" => "HK","code" => "+852"),
		"HN" => array("currency" => "HNL","currency_symbol" => "&#76;","name" => "HONDURAS","short_name" => "HN","code" => "+504"),
		"HR" => array("currency" => "HRK","currency_symbol" => "&#107;&#110;","name" => "CROATIA","short_name" => "HR","code" => "+385"),
		"HT" => array("currency" => "HTG","currency_symbol" => "&#71;","name" => "HAITI","short_name" => "HT","code" => "+509"),
		"HU" => array("currency" => "HUF","currency_symbol" => "&#70;&#116;","name" => "HUNGARY","short_name" => "HU","code" => "+36"),
		"ID" => array("currency" => "IDR","currency_symbol" => "&#82;&#112;","name" => "INDONESIA","short_name" => "ID","code" => "+62"),
		"IE" => array("currency" => "EUR","currency_symbol" => "&#8364;","name" => "IRELAND","short_name" => "IE","code" => "+353"),
		"IL" => array("currency" => "ILS","currency_symbol" => "&#8362;","name" => "ISRAEL","short_name" => "IL","code" => "+972"),
		"IM" => array("currency" => "GBP","currency_symbol" => "&#163;","name" => "ISLE OF MAN","short_name" => "IM","code" => "+44"),
		"IN" => array("currency" => "INR","currency_symbol" => "&#8377;","name" => "INDIA","short_name" => "IN","code" => "+91"),
		"IQ" => array("currency" => "IQD","currency_symbol" => "&#1593;.&#1583;","name" => "IRAQ","short_name" => "IQ","code" => "+964"),
		"IR" => array("currency" => "IRR","currency_symbol" => "&#65020;","name" => "IRAN","short_name" => "IR","code" => "+98"),
		"IS" => array("currency" => "ISK","currency_symbol" => "&#107;&#114;","name" => "ICELAND","short_name" => "IS","code" => "+354"),
		"IT" => array("currency" => "EUR","currency_symbol" => "&#8364;","name" => "ITALY","short_name" => "IT","code" => "+39"),
		"JM" => array("currency" => "JMD","currency_symbol" => "&#74;&#36;","name" => "JAMAICA","short_name" => "JM","code" => "+1876"),
		"JO" => array("currency" => "JOD","currency_symbol" => "&#74;&#68;","name" => "JORDAN","short_name" => "JO","code" => "+962"),
		"JP" => array("currency" => "JPY","currency_symbol" => "&#165;","name" => "JAPAN","short_name" => "JP","code" => "+81"),
		"KE" => array("currency" => "KES","currency_symbol" => "&#75;&#83;&#104;","name" => "KENYA","short_name" => "KE","code" => "+254"),
		"KG" => array("currency" => "KGS","currency_symbol" => "&#1083;&#1074;","name" => "KYRGYZSTAN","short_name" => "KG","code" => "+996"),
		"KH" => array("currency" => "KHR","currency_symbol" => "&#6107;","name" => "CAMBODIA","short_name" => "KH","code" => "+855"),
		"KI" => array("currency" => "AUD","currency_symbol" => "&#36;","name" => "KIRIBATI","short_name" => "KI","code" => "+686"),
		"KM" => array("currency" => "KMF","currency_symbol" => "&#67;&#70;","name" => "COMOROS","short_name" => "KM","code" => "+269"),
		"KN" => array("currency" => "XCD","currency_symbol" => "&#36;","name" => "SAINT KITTS AND NEVIS","short_name" => "KN","code" => "+1869"),
		"KP" => array("currency" => "KPW","currency_symbol" => "&#8361;","name" => "KOREA DEMOCRATIC PEOPLES REPUBLIC","short_name" => "KP","code" => "+850"),
		"KR" => array("currency" => "KRW","currency_symbol" => "&#8361;","name" => "KOREA REPUBLIC","short_name" => "KR","code" => "+82"),
		"KW" => array("currency" => "KWD","currency_symbol" => "&#1583;.&#1603;","name" => "KUWAIT","short_name" => "KW","code" => "+965"),
		"KY" => array("currency" => "KYD","currency_symbol" => "&#36;","name" => "CAYMAN ISLANDS","short_name" => "KY","code" => "+1345"),
		"KZ" => array("currency" => "KZT","currency_symbol" => "&#1083;&#1074;","name" => "KAZAKHSTAN","short_name" => "KZ","code" => "+7"),
		"LA" => array("currency" => "LAK","currency_symbol" => "&#8365;","name" => "LAO PEOPLES DEMOCRATIC REPUBLIC","short_name" => "LA","code" => "+856"),
		"LB" => array("currency" => "LBP","currency_symbol" => "&#163;","name" => "LEBANON","short_name" => "LB","code" => "+961"),
		"LC" => array("currency" => "XCD","currency_symbol" => "&#36;","name" => "SAINT LUCIA","short_name" => "LC","code" => "+1758"),
		"LI" => array("currency" => "CHF","currency_symbol" => "&#67;&#72;&#70;","name" => "LIECHTENSTEIN","short_name" => "LI","code" => "+423"),
		"LK" => array("currency" => "LKR","currency_symbol" => "&#8360;","name" => "SRI LANKA","short_name" => "LK","code" => "+94"),
		"LR" => array("currency" => "LRD","currency_symbol" => "&#36;","name" => "LIBERIA","short_name" => "LR","code" => "+231"),
		"LS" => array("currency" => "LSL","currency_symbol" => "&#76;","name" => "LESOTHO","short_name" => "LS","code" => "+266"),
		"LT" => array("currency" => "EUR","currency_symbol" => "&#8364;","name" => "LITHUANIA","short_name" => "LT","code" => "+370"),
		"LU" => array("currency" => "EUR","currency_symbol" => "&#8364;","name" => "LUXEMBOURG","short_name" => "LU","code" => "+352"),
		"LV" => array("currency" => "EUR","currency_symbol" => "&#8364;","name" => "LATVIA","short_name" => "LV","code" => "+371"),
		"LY" => array("currency" => "LYD","currency_symbol" => "&#1604;.&#1583;","name" => "LIBYAN ARAB JAMAHIRIYA","short_name" => "LY","code" => "+218"),
		"MA" => array("currency" => "MAD","currency_symbol" => "&#1583;.&#1605;.","name" => "MOROCCO","short_name" => "MA","code" => "+212"),
		"MC" => array("currency" => "EUR","currency_symbol" => "&#8364;","name" => "MONACO","short_name" => "MC","code" => "+377"),
		"MD" => array("currency" => "MDL","currency_symbol" => "&#76;","name" => "MOLDOVA, REPUBLIC OF","short_name" => "MD","code" => "+373"),
		"ME" => array("currency" => "EUR","currency_symbol" => "&#8364;","name" => "MONTENEGRO","short_name" => "ME","code" => "+382"),
		"MF" => array("currency" => "","currency_symbol" => "","name" => "SAINT MARTIN","short_name" => "MF","code" => "+1599"),
		"MG" => array("currency" => "MGA","currency_symbol" => "Ar","name" => "MADAGASCAR","short_name" => "MG","code" => "+261"),
		"MH" => array("currency" => "USD","currency_symbol" => "&#36;","name" => "MARSHALL ISLANDS","short_name" => "MH","code" => "+692"),
		"MK" => array("currency" => "MKD","currency_symbol" => "&#1076;&#1077;&#1085;","name" => "MACEDONIA","short_name" => "MK","code" => "+389"),
		"ML" => array("currency" => "XOF","currency_symbol" => "CFA","name" => "MALI","short_name" => "ML","code" => "+223"),
		"MM" => array("currency" => "MMK","currency_symbol" => "&#75;","name" => "MYANMAR","short_name" => "MM","code" => "+95"),
		"MN" => array("currency" => "MNT","currency_symbol" => "&#8366;","name" => "MONGOLIA","short_name" => "MN","code" => "+976"),
		"MO" => array("currency" => "","currency_symbol" => "","name" => "MACAU","short_name" => "MO","code" => "+853"),
		"MP" => array("currency" => "USD","currency_symbol" => "&#36;","name" => "NORTHERN MARIANA ISLANDS","short_name" => "MP","code" => "+1670"),
		"MR" => array("currency" => "MRO","currency_symbol" => "&#85;&#77;","name" => "MAURITANIA","short_name" => "MR","code" => "+222"),
		"MS" => array("currency" => "XCD","currency_symbol" => "&#36;","name" => "MONTSERRAT","short_name" => "MS","code" => "+1664"),
		"MT" => array("currency" => "EUR","currency_symbol" => "&#8364;","name" => "MALTA","short_name" => "MT","code" => "+356"),
		"MU" => array("currency" => "MUR","currency_symbol" => "&#8360;","name" => "MAURITIUS","short_name" => "MU","code" => "+230"),
		"MV" => array("currency" => "MVR","currency_symbol" => ".&#1923;","name" => "MALDIVES","short_name" => "MV","code" => "+960"),
		"MW" => array("currency" => "MWK","currency_symbol" => "&#77;&#75;","name" => "MALAWI","short_name" => "MW","code" => "+265"),
		"MX" => array("currency" => "MXN","currency_symbol" => "&#36;","name" => "MEXICO","short_name" => "MX","code" => "+52"),
		"MY" => array("currency" => "MYR","currency_symbol" => "&#82;&#77;","name" => "MALAYSIA","short_name" => "MY","code" => "+60"),
		"MZ" => array("currency" => "MZN","currency_symbol" => "&#77;&#84;","name" => "MOZAMBIQUE","short_name" => "MZ","code" => "+258"),
		"NA" => array("currency" => "NAD","currency_symbol" => "&#36;","name" => "NAMIBIA","short_name" => "NA","code" => "+264"),
		"NC" => array("currency" => "XPF","currency_symbol" => "&#70;","name" => "NEW CALEDONIA","short_name" => "NC","code" => "+687"),
		"NE" => array("currency" => "XOF","currency_symbol" => "CFA","name" => "NIGER","short_name" => "NE","code" => "+227"),
		"NG" => array("currency" => "NGN","currency_symbol" => "&#8358;","name" => "NIGERIA","short_name" => "NG","code" => "+234"),
		"NI" => array("currency" => "NIO","currency_symbol" => "&#67;&#36;","name" => "NICARAGUA","short_name" => "NI","code" => "+505"),
		"NL" => array("currency" => "EUR","currency_symbol" => "&#8364;","name" => "NETHERLANDS","short_name" => "NL","code" => "+31"),
		"NO" => array("currency" => "NOK","currency_symbol" => "&#107;&#114;","name" => "NORWAY","short_name" => "NO","code" => "+47"),
		"NP" => array("currency" => "NPR","currency_symbol" => "&#8360;","name" => "NEPAL","short_name" => "NP","code" => "+977"),
		"NR" => array("currency" => "AUD","currency_symbol" => "&#36;","name" => "NAURU","short_name" => "NR","code" => "+674"),
		"NU" => array("currency" => "NZD","currency_symbol" => "&#36;","name" => "NIUE","short_name" => "NU","code" => "+683"),
		"NZ" => array("currency" => "NZD","currency_symbol" => "&#36;","name" => "NEW ZEALAND","short_name" => "NZ","code" => "+64"),
		"OM" => array("currency" => "OMR","currency_symbol" => "&#65020;","name" => "OMAN","short_name" => "OM","code" => "+968"),
		"PA" => array("currency" => "PAB","currency_symbol" => "&#66;&#47;&#46;","name" => "PANAMA","short_name" => "PA","code" => "+507"),
		"PE" => array("currency" => "PEN","currency_symbol" => "&#83;&#47;&#46;","name" => "PERU","short_name" => "PE","code" => "+51"),
		"PF" => array("currency" => "XPF","currency_symbol" => "F","name" => "FRENCH POLYNESIA","short_name" => "PF","code" => "+689"),
		"PH" => array("currency" => "PHP","currency_symbol" => "&#8369;","name" => "PHILIPPINES","short_name" => "PH","code" => "+63"),
		"PK" => array("currency" => "PKR","currency_symbol" => "&#8360;","name" => "PAKISTAN","short_name" => "PK","code" => "+92"),
		"PL" => array("currency" => "PLN","currency_symbol" => "&#122;&#322;","name" => "POLAND","short_name" => "PL","code" => "+48"),
		"PM" => array("currency" => "EUR","currency_symbol" => "&#8364;","name" => "SAINT PIERRE AND MIQUELON","short_name" => "PM","code" => "+508"),
		"PN" => array("currency" => "NZD","currency_symbol" => "&#36;","name" => "PITCAIRN","short_name" => "PN","code" => "+870"),
		"PR" => array("currency" => "USD","currency_symbol" => "&#36;","name" => "PUERTO RICO","short_name" => "PR","code" => "+1"),
		"PT" => array("currency" => "EUR","currency_symbol" => "&#8364;","name" => "PORTUGAL","short_name" => "PT","code" => "+351"),
		"PW" => array("currency" => "USD","currency_symbol" => "&#36;","name" => "PALAU","short_name" => "PW","code" => "+680"),
		"PY" => array("currency" => "PYG","currency_symbol" => "&#71;&#115;","name" => "PARAGUAY","short_name" => "PY","code" => "+595"),
		"QA" => array("currency" => "QAR","currency_symbol" => "&#65020;","name" => "QATAR","short_name" => "QA","code" => "+974"),
		"RO" => array("currency" => "RON","currency_symbol" => "&#108;&#101;&#105;","name" => "ROMANIA","short_name" => "RO","code" => "+40"),
		"RS" => array("currency" => "RSD","currency_symbol" => "&#1044;&#1080;&#1085;&#46;","name" => "SERBIA","short_name" => "RS","code" => "+381"),
		"RU" => array("currency" => "RUB","currency_symbol" => "&#1088;&#1091;&#1073;","name" => "RUSSIAN FEDERATION","short_name" => "RU","code" => "+7"),
		"RW" => array("currency" => "RWF","currency_symbol" => "&#1585;.&#1587;","name" => "RWANDA","short_name" => "RW","code" => "+250"),
		"SA" => array("currency" => "SAR","currency_symbol" => "&#65020;","name" => "SAUDI ARABIA","short_name" => "SA","code" => "+966"),
		"SB" => array("currency" => "SBD","currency_symbol" => "&#36;","name" => "SOLOMON ISLANDS","short_name" => "SB","code" => "+677"),
		"SC" => array("currency" => "SCR","currency_symbol" => "&#8360;","name" => "SEYCHELLES","short_name" => "SC","code" => "+248"),
		"SD" => array("currency" => "SDG","currency_symbol" => "&#163;","name" => "SUDAN","short_name" => "SD","code" => "+249"),
		"SE" => array("currency" => "SEK","currency_symbol" => "&#107;&#114;","name" => "SWEDEN","short_name" => "SE","code" => "+46"),
		"SG" => array("currency" => "SGD","currency_symbol" => "&#36;","name" => "SINGAPORE","short_name" => "SG","code" => "+65"),
		"SH" => array("currency" => "SHP","currency_symbol" => "&#163;","name" => "SAINT HELENA","short_name" => "SH","code" => "+290"),
		"SI" => array("currency" => "EUR","currency_symbol" => "&#8364;","name" => "SLOVENIA","short_name" => "SI","code" => "+386"),
		"SK" => array("currency" => "EUR","currency_symbol" => "&#8364;","name" => "SLOVAKIA","short_name" => "SK","code" => "+421"),
		"SL" => array("currency" => "SLL","currency_symbol" => "&#76;&#101;","name" => "SIERRA LEONE","short_name" => "SL","code" => "+232"),
		"SM" => array("currency" => "EUR","currency_symbol" => "&#8364;","name" => "SAN MARINO","short_name" => "SM","code" => "+378"),
		"SN" => array("currency" => "XOF","currency_symbol" => "CFA","name" => "SENEGAL","short_name" => "SN","code" => "+221"),
		"SO" => array("currency" => "SOS","currency_symbol" => "&#83;","name" => "SOMALIA","short_name" => "SO","code" => "+252"),
		"SR" => array("currency" => "SRD","currency_symbol" => "&#36;","name" => "SURINAME","short_name" => "SR","code" => "+597"),
		"ST" => array("currency" => "STD","currency_symbol" => "&#68;&#98;","name" => "SAO TOME AND PRINCIPE","short_name" => "ST","code" => "+239"),
		"SV" => array("currency" => "SVC","currency_symbol" => "&#36;","name" => "EL SALVADOR","short_name" => "SV","code" => "+503"),
		"SY" => array("currency" => "SYP","currency_symbol" => "&#163;","name" => "SYRIAN ARAB REPUBLIC","short_name" => "SY","code" => "+963"),
		"SZ" => array("currency" => "SZL","currency_symbol" => "&#76;","name" => "SWAZILAND","short_name" => "SZ","code" => "+268"),
		"TC" => array("currency" => "USD","currency_symbol" => "&#36;","name" => "TURKS AND CAICOS ISLANDS","short_name" => "TC","code" => "+1649"),
		"TD" => array("currency" => "XAF","currency_symbol" => "&#70;&#67;&#70;&#65;","name" => "CHAD","short_name" => "TD","code" => "+235"),
		"TG" => array("currency" => "XOF","currency_symbol" => "CFA","name" => "TOGO","short_name" => "TG","code" => "+228"),
		"TH" => array("currency" => "THB","currency_symbol" => "&#3647;","name" => "THAILAND","short_name" => "TH","code" => "+66"),
		"TJ" => array("currency" => "TJS","currency_symbol" => "&#84;&#74;&#83;","name" => "TAJIKISTAN","short_name" => "TJ","code" => "+992"),
		"TK" => array("currency" => "NZD","currency_symbol" => "&#36;","name" => "TOKELAU","short_name" => "TK","code" => "+690"),
		"TL" => array("currency" => "USD","currency_symbol" => "&#36;","name" => "TIMOR-LESTE","short_name" => "TL","code" => "+670"),
		"TM" => array("currency" => "TMT","currency_symbol" => "&#109;","name" => "TURKMENISTAN","short_name" => "TM","code" => "+993"),
		"TN" => array("currency" => "TND","currency_symbol" => "&#1583;.&#1578;","name" => "TUNISIA","short_name" => "TN","code" => "+216"),
		"TO" => array("currency" => "TOP","currency_symbol" => "&#84;&#36;","name" => "TONGA","short_name" => "TO","code" => "+676"),
		"TR" => array("currency" => "TRY","currency_symbol" => "&#8356;","name" => "TURKEY","short_name" => "TR","code" => "+90"),
		"TT" => array("currency" => "TTD","currency_symbol" => "&#36;","name" => "TRINIDAD AND TOBAGO","short_name" => "TT","code" => "+1868"),
		"TV" => array("currency" => "AUD","currency_symbol" => "&#36;","name" => "TUVALU","short_name" => "TV","code" => "+688"),
		"TW" => array("currency" => "TWD","currency_symbol" => "&#78;&#84;&#36;","name" => "TAIWAN","short_name" => "TW","code" => "+886"),
		"TZ" => array("currency" => "TZS","currency_symbol" => "TSH","name" => "TANZANIA","short_name" => "TZ","code" => "+255"),
		"UA" => array("currency" => "UAH","currency_symbol" => "&#8372;","name" => "UKRAINE","short_name" => "UA","code" => "+380"),
		"UG" => array("currency" => "UGX","currency_symbol" => "&#85;&#83;&#104;","name" => "UGANDA","short_name" => "UG","code" => "+256"),
		"US" => array("currency" => "USD","currency_symbol" => "&#36;","name" => "UNITED STATES","short_name" => "US","code" => "+1"),
		"UY" => array("currency" => "UYU","currency_symbol" => "&#36;&#85;","name" => "URUGUAY","short_name" => "UY","code" => "+598"),
		"UZ" => array("currency" => "UZS","currency_symbol" => "&#1083;&#1074;","name" => "UZBEKISTAN","short_name" => "UZ","code" => "+998"),
		"VA" => array("currency" => "EUR","currency_symbol" => "&#8364;","name" => "VATICAN CITY","short_name" => "VA","code" => "+39"),
		"VC" => array("currency" => "XCD","currency_symbol" => "&#36;","name" => "SAINT VINCENT AND THE GRENADINES","short_name" => "VC","code" => "+1784"),
		"VE" => array("currency" => "VEF","currency_symbol" => "&#66;&#115;","name" => "VENEZUELA","short_name" => "VE","code" => "+58"),
		"VG" => array("currency" => "USD","currency_symbol" => "&#36;","name" => "BRITISH VIRGIN ISLANDS","short_name" => "VG","code" => "+1284"),
		"VI" => array("currency" => "USD","currency_symbol" => "&#36;","name" => "VIRGIN ISLANDS, U.S.","short_name" => "VI","code" => "+1340"),
		"VN" => array("currency" => "VND","currency_symbol" => "&#8363;","name" => "VIETNAM","short_name" => "VN","code" => "+84"),
		"VU" => array("currency" => "VUV","currency_symbol" => "&#86;&#84;","name" => "VANUATU","short_name" => "VU","code" => "+678"),
		"WF" => array("currency" => "XPF","currency_symbol" => "&#70;","name" => "WALLIS AND FUTUNA","short_name" => "WF","code" => "+681"),
		"WS" => array("currency" => "WST","currency_symbol" => "&#87;&#83;&#36;","name" => "SAMOA","short_name" => "WS","code" => "+685"),
		"XK" => array("currency" => "EUR","currency_symbol" => "&#8364;","name" => "KOSOVO","short_name" => "XK","code" => "+381"),
		"YE" => array("currency" => "YER","currency_symbol" => "&#65020;","name" => "YEMEN","short_name" => "YE","code" => "+967"),
		"YT" => array("currency" => "EUR","currency_symbol" => "&#8364;","name" => "MAYOTTE","short_name" => "YT","code" => "+262"),
		"ZA" => array("currency" => "ZAR","currency_symbol" => "&#82;","name" => "SOUTH AFRICA","short_name" => "ZA","code" => "+27"),
		"ZM" => array("currency" => "ZMW","currency_symbol" => "ZK","name" => "ZAMBIA","short_name" => "ZM","code" => "+260"),
		"ZW" => array("currency" => "ZWD","currency_symbol" => "&#36;","name" => "ZIMBABWE","short_name" => "ZW","code" => "+263"),
	);
