<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'Test\\' => array($baseDir . '/../test'),
    'Root\\' => array($baseDir . '/../..'),
    'Luminova\\SessionManager\\' => array($baseDir . '/Session'),
    'Luminova\\Seo\\' => array($baseDir . '/Seo'),
    'Luminova\\Security\\' => array($baseDir . '/Security'),
    'Luminova\\Logger\\' => array($baseDir . '/Logger'),
    'Luminova\\Functions\\' => array($baseDir . '/Functions'),
    'Luminova\\Exceptions\\' => array($baseDir . '/Exceptions'),
    'Luminova\\DatabaseManager\\' => array($baseDir . '/Database'),
    'Luminova\\Config\\' => array($baseDir . '/Config'),
    'Luminova\\Cache\\' => array($baseDir . '/Cache'),
    'Luminova\\' => array($baseDir . '/'),
    'App\\Controllers\\' => array($baseDir . '/../app/Controllers'),
);
