<?php

// autoload_classmap.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname(dirname($vendorDir));

return array(
    'App\\Controllers\\Config' => $baseDir . '/app/Controllers/Config.php',
    'App\\Controllers\\Func' => $baseDir . '/app/Controllers/Func.php',
    'App\\Controllers\\HelloWorld' => $baseDir . '/app/Controllers/HelloWorld.php',
    'Composer\\InstalledVersions' => $vendorDir . '/composer/InstalledVersions.php',
    'Luminova\\AppController' => $baseDir . '/system/AppController.php',
    'Luminova\\Arrays\\ArrayInput' => $baseDir . '/system/Arrays/ArrayInput.php',
    'Luminova\\BaseController' => $baseDir . '/system/BaseController.php',
    'Luminova\\Cache\\Compress' => $baseDir . '/system/Cache/Compress.php',
    'Luminova\\Cache\\Optimizer' => $baseDir . '/system/Cache/Optimizer.php',
    'Luminova\\Cache\\SystemCache' => $baseDir . '/system/Cache/SystemCache.php',
    'Luminova\\Command\\AppCommand' => $baseDir . '/system/Command/AppCommand.php',
    'Luminova\\Command\\Create' => $baseDir . '/system/Command/Create.php',
    'Luminova\\Command\\Plugin' => $baseDir . '/system/Command/Plugin.php',
    'Luminova\\Command\\RebuildCommand' => $baseDir . '/system/Command/RebuildCommand.php',
    'Luminova\\Command\\Subscriber' => $baseDir . '/system/Command/Subscriber.php',
    'Luminova\\ComposerAutoUpdater' => $baseDir . '/system/ComposerAutoUpdater.php',
    'Luminova\\Config\\ConfigManager' => $baseDir . '/system/Config/ConfigManager.php',
    'Luminova\\Config\\DotEnv' => $baseDir . '/system/Config/DotEnv.php',
    'Luminova\\Config\\PHPStanRules' => $baseDir . '/system/Config/PHPStanRules.php',
    'Luminova\\Database\\Columns' => $baseDir . '/system/Database/Columns.php',
    'Luminova\\Database\\Conn' => $baseDir . '/system/Database/Conn.php',
    'Luminova\\Database\\Mysqli' => $baseDir . '/system/Database/Mysqli.php',
    'Luminova\\Database\\Pdo' => $baseDir . '/system/Database/Pdo.php',
    'Luminova\\Database\\Query' => $baseDir . '/system/Database/Query.php',
    'Luminova\\Exceptions\\ClassNotFoundException' => $baseDir . '/system/Exceptions/ClassNotFoundException.php',
    'Luminova\\Exceptions\\DatabaseException' => $baseDir . '/system/Exceptions/DatabaseException.php',
    'Luminova\\Exceptions\\FileNotFoundException' => $baseDir . '/system/Exceptions/FileNotFoundException.php',
    'Luminova\\Exceptions\\InvalidArgumentException' => $baseDir . '/system/Exceptions/InvalidArgumentException.php',
    'Luminova\\Exceptions\\PageNotFoundException' => $baseDir . '/system/Exceptions/PageNotFoundException.php',
    'Luminova\\Functions' => $baseDir . '/system/Functions.php',
    'Luminova\\Functions\\FunctionInterface' => $baseDir . '/system/Functions/FunctionInterface.php',
    'Luminova\\Functions\\Functions' => $baseDir . '/system/Functions/Functions.php',
    'Luminova\\Logger\\FileLogger' => $baseDir . '/system/Logger/FileLogger.php',
    'Luminova\\Logger\\LoggerInterface' => $baseDir . '/system/Logger/LoggerInterface.php',
    'Luminova\\RequestHandler' => $baseDir . '/system/RequestHandler.php',
    'Luminova\\Router' => $baseDir . '/system/Router.php',
    'Luminova\\Security\\CsrfToken' => $baseDir . '/system/Security/CsrfToken.php',
    'Luminova\\Seo\\MetaObjectGraph' => $baseDir . '/system/Seo/MetaObjectGraph.php',
    'Luminova\\Sessions\\Session' => $baseDir . '/system/Sessions/Session.php',
    'Luminova\\Template' => $baseDir . '/system/Template.php',
);
