<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname(dirname($vendorDir));

return array(
    'Psr\\Log\\' => array($vendorDir . '/psr/log/Psr/Log'),
    'PHPMailer\\PHPMailer\\' => array($vendorDir . '/phpmailer/phpmailer/src'),
    'Luminova\\Time\\' => array($baseDir . '/system/Time'),
    'Luminova\\Template\\' => array($baseDir . '/system/Template'),
    'Luminova\\Storage\\' => array($baseDir . '/system/Storage'),
    'Luminova\\Sessions\\' => array($baseDir . '/system/Sessions'),
    'Luminova\\Seo\\' => array($baseDir . '/system/Seo'),
    'Luminova\\Security\\Encryption\\' => array($baseDir . '/system/Security/Encryption'),
    'Luminova\\Security\\' => array($baseDir . '/system/Security'),
    'Luminova\\Routing\\' => array($baseDir . '/system/Routing'),
    'Luminova\\Notifications\\' => array($baseDir . '/system/Notifications'),
    'Luminova\\Models\\' => array($baseDir . '/system/Models'),
    'Luminova\\Logger\\' => array($baseDir . '/system/Logger'),
    'Luminova\\Languages\\' => array($baseDir . '/system/Languages'),
    'Luminova\\Http\\' => array($baseDir . '/system/Http'),
    'Luminova\\Functions\\' => array($baseDir . '/system/Functions'),
    'Luminova\\Exceptions\\' => array($baseDir . '/system/Exceptions'),
    'Luminova\\Errors\\' => array($baseDir . '/system/Errors'),
    'Luminova\\Database\\Drivers\\' => array($baseDir . '/system/Database/Drivers'),
    'Luminova\\Database\\' => array($baseDir . '/system/Database'),
    'Luminova\\Config\\' => array($baseDir . '/system/Config'),
    'Luminova\\Composer\\' => array($baseDir . '/system/Composer'),
    'Luminova\\Command\\' => array($baseDir . '/system/Command'),
    'Luminova\\Cache\\' => array($baseDir . '/system/Cache'),
    'Luminova\\Arrays\\' => array($baseDir . '/system/Arrays'),
    'Luminova\\' => array($baseDir . '/system'),
    'App\\Controllers\\Models\\' => array($baseDir . '/app/Controllers/Models'),
    'App\\Controllers\\Config\\' => array($baseDir . '/app/Controllers/Config'),
    'App\\Controllers\\' => array($baseDir . '/app/Controllers'),
);
