<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit9c155849e043191fc1df7e0b46712cd7
{
    public static $prefixLengthsPsr4 = array (
        'P' => 
        array (
            'Psr\\Log\\' => 8,
        ),
        'L' => 
        array (
            'Luminova\\Utils\\' => 15,
            'Luminova\\Time\\' => 14,
            'Luminova\\Template\\' => 18,
            'Luminova\\Storage\\' => 17,
            'Luminova\\Sessions\\' => 18,
            'Luminova\\Seo\\' => 13,
            'Luminova\\Security\\Encryption\\' => 29,
            'Luminova\\Security\\' => 18,
            'Luminova\\Router\\' => 16,
            'Luminova\\Notifications\\' => 23,
            'Luminova\\Models\\' => 16,
            'Luminova\\Logger\\' => 16,
            'Luminova\\Languages\\' => 19,
            'Luminova\\Http\\Client\\' => 21,
            'Luminova\\Http\\' => 14,
            'Luminova\\Functions\\' => 19,
            'Luminova\\Exceptions\\' => 20,
            'Luminova\\Errors\\' => 16,
            'Luminova\\Database\\Drivers\\' => 26,
            'Luminova\\Database\\' => 18,
            'Luminova\\Controller\\' => 20,
            'Luminova\\Config\\' => 16,
            'Luminova\\Composer\\' => 18,
            'Luminova\\Command\\' => 17,
            'Luminova\\Cache\\' => 15,
            'Luminova\\Base\\' => 14,
            'Luminova\\Arrays\\' => 16,
            'Luminova\\Application\\' => 21,
            'Luminova\\' => 9,
        ),
        'A' => 
        array (
            'App\\Controllers\\Models\\' => 23,
            'App\\Controllers\\Config\\' => 23,
            'App\\Controllers\\' => 16,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Psr\\Log\\' => 
        array (
            0 => __DIR__ . '/..' . '/psr/log/Psr/Log',
        ),
        'Luminova\\Utils\\' => 
        array (
            0 => __DIR__ . '/../../..' . '/system/Utils',
        ),
        'Luminova\\Time\\' => 
        array (
            0 => __DIR__ . '/../../..' . '/system/Time',
        ),
        'Luminova\\Template\\' => 
        array (
            0 => __DIR__ . '/../../..' . '/system/Template',
        ),
        'Luminova\\Storage\\' => 
        array (
            0 => __DIR__ . '/../../..' . '/system/Storage',
        ),
        'Luminova\\Sessions\\' => 
        array (
            0 => __DIR__ . '/../../..' . '/system/Sessions',
        ),
        'Luminova\\Seo\\' => 
        array (
            0 => __DIR__ . '/../../..' . '/system/Seo',
        ),
        'Luminova\\Security\\Encryption\\' => 
        array (
            0 => __DIR__ . '/../../..' . '/system/Security/Encryption',
        ),
        'Luminova\\Security\\' => 
        array (
            0 => __DIR__ . '/../../..' . '/system/Security',
        ),
        'Luminova\\Router\\' => 
        array (
            0 => __DIR__ . '/../../..' . '/system/Router',
        ),
        'Luminova\\Notifications\\' => 
        array (
            0 => __DIR__ . '/../../..' . '/system/Notifications',
        ),
        'Luminova\\Models\\' => 
        array (
            0 => __DIR__ . '/../../..' . '/system/Models',
        ),
        'Luminova\\Logger\\' => 
        array (
            0 => __DIR__ . '/../../..' . '/system/Logger',
        ),
        'Luminova\\Languages\\' => 
        array (
            0 => __DIR__ . '/../../..' . '/system/Languages',
        ),
        'Luminova\\Http\\Client\\' => 
        array (
            0 => __DIR__ . '/../../..' . '/system/Http/Client',
        ),
        'Luminova\\Http\\' => 
        array (
            0 => __DIR__ . '/../../..' . '/system/Http',
        ),
        'Luminova\\Functions\\' => 
        array (
            0 => __DIR__ . '/../../..' . '/system/Functions',
        ),
        'Luminova\\Exceptions\\' => 
        array (
            0 => __DIR__ . '/../../..' . '/system/Exceptions',
        ),
        'Luminova\\Errors\\' => 
        array (
            0 => __DIR__ . '/../../..' . '/system/Errors',
        ),
        'Luminova\\Database\\Drivers\\' => 
        array (
            0 => __DIR__ . '/../../..' . '/system/Database/Drivers',
        ),
        'Luminova\\Database\\' => 
        array (
            0 => __DIR__ . '/../../..' . '/system/Database',
        ),
        'Luminova\\Controller\\' => 
        array (
            0 => __DIR__ . '/../../..' . '/system/Controller',
        ),
        'Luminova\\Config\\' => 
        array (
            0 => __DIR__ . '/../../..' . '/system/Config',
        ),
        'Luminova\\Composer\\' => 
        array (
            0 => __DIR__ . '/../../..' . '/system/Composer',
        ),
        'Luminova\\Command\\' => 
        array (
            0 => __DIR__ . '/../../..' . '/system/Command',
        ),
        'Luminova\\Cache\\' => 
        array (
            0 => __DIR__ . '/../../..' . '/system/Cache',
        ),
        'Luminova\\Base\\' => 
        array (
            0 => __DIR__ . '/../../..' . '/system/Base',
        ),
        'Luminova\\Arrays\\' => 
        array (
            0 => __DIR__ . '/../../..' . '/system/Arrays',
        ),
        'Luminova\\Application\\' => 
        array (
            0 => __DIR__ . '/../../..' . '/system/Application',
        ),
        'Luminova\\' => 
        array (
            0 => __DIR__ . '/../../..' . '/system',
        ),
        'App\\Controllers\\Models\\' => 
        array (
            0 => __DIR__ . '/../../..' . '/app/Controllers/Models',
        ),
        'App\\Controllers\\Config\\' => 
        array (
            0 => __DIR__ . '/../../..' . '/app/Controllers/Config',
        ),
        'App\\Controllers\\' => 
        array (
            0 => __DIR__ . '/../../..' . '/app/Controllers',
        ),
    );

    public static $classMap = array (
        'App\\Controllers\\Application' => __DIR__ . '/../../..' . '/app/Controllers/Application.php',
        'App\\Controllers\\Command' => __DIR__ . '/../../..' . '/app/Controllers/Command.php',
        'App\\Controllers\\Config\\Session' => __DIR__ . '/../../..' . '/app/Controllers/Config/Session.php',
        'App\\Controllers\\Welcome' => __DIR__ . '/../../..' . '/app/Controllers/Welcome.php',
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
        'Luminova\\Application\\Application' => __DIR__ . '/../../..' . '/system/Application/Application.php',
        'Luminova\\Arrays\\ArrayCountable' => __DIR__ . '/../../..' . '/system/Arrays/ArrayCountable.php',
        'Luminova\\Arrays\\ArrayInput' => __DIR__ . '/../../..' . '/system/Arrays/ArrayInput.php',
        'Luminova\\Arrays\\Arrays' => __DIR__ . '/../../..' . '/system/Arrays/Arrays.php',
        'Luminova\\Base\\BaseApplication' => __DIR__ . '/../../..' . '/system/Base/BaseApplication.php',
        'Luminova\\Base\\BaseCommand' => __DIR__ . '/../../..' . '/system/Base/BaseCommand.php',
        'Luminova\\Base\\BaseController' => __DIR__ . '/../../..' . '/system/Base/BaseController.php',
        'Luminova\\Base\\BaseModel' => __DIR__ . '/../../..' . '/system/Base/BaseModel.php',
        'Luminova\\Cache\\Cache' => __DIR__ . '/../../..' . '/system/Cache/Cache.php',
        'Luminova\\Cache\\Compress' => __DIR__ . '/../../..' . '/system/Cache/Compress.php',
        'Luminova\\Cache\\FileCacheItem' => __DIR__ . '/../../..' . '/system/Cache/FileCacheItem.php',
        'Luminova\\Cache\\FileSystemCache' => __DIR__ . '/../../..' . '/system/Cache/FileSystemCache.php',
        'Luminova\\Cache\\MemoryCache' => __DIR__ . '/../../..' . '/system/Cache/MemoryCache.php',
        'Luminova\\Cache\\Optimizer' => __DIR__ . '/../../..' . '/system/Cache/Optimizer.php',
        'Luminova\\Command\\Colors' => __DIR__ . '/../../..' . '/system/Command/Colors.php',
        'Luminova\\Command\\Commands' => __DIR__ . '/../../..' . '/system/Command/Commands.php',
        'Luminova\\Command\\Console' => __DIR__ . '/../../..' . '/system/Command/Console.php',
        'Luminova\\Command\\Terminal' => __DIR__ . '/../../..' . '/system/Command/Terminal.php',
        'Luminova\\Command\\TerminalGenerator' => __DIR__ . '/../../..' . '/system/Command/TerminalGenerator.php',
        'Luminova\\Command\\TextUtils' => __DIR__ . '/../../..' . '/system/Command/TextUtils.php',
        'Luminova\\Composer\\BaseComposer' => __DIR__ . '/../../..' . '/system/Composer/BaseComposer.php',
        'Luminova\\Composer\\Builder' => __DIR__ . '/../../..' . '/system/Composer/Builder.php',
        'Luminova\\Composer\\Updater' => __DIR__ . '/../../..' . '/system/Composer/Updater.php',
        'Luminova\\Config\\Configuration' => __DIR__ . '/../../..' . '/system/Config/Configuration.php',
        'Luminova\\Config\\Database' => __DIR__ . '/../../..' . '/system/Config/Database.php',
        'Luminova\\Config\\DotEnv' => __DIR__ . '/../../..' . '/system/Config/DotEnv.php',
        'Luminova\\Config\\PHPStanRules' => __DIR__ . '/../../..' . '/system/Config/PHPStanRules.php',
        'Luminova\\Config\\SystemPaths' => __DIR__ . '/../../..' . '/system/Config/SystemPaths.php',
        'Luminova\\Controllers\\Controller' => __DIR__ . '/../../..' . '/system/Controllers/Controller.php',
        'Luminova\\Database\\Columns' => __DIR__ . '/../../..' . '/system/Database/Columns.php',
        'Luminova\\Database\\Conn' => __DIR__ . '/../../..' . '/system/Database/Conn.php',
        'Luminova\\Database\\DatabaseInterface' => __DIR__ . '/../../..' . '/system/Database/DatabaseInterface.php',
        'Luminova\\Database\\Drivers\\MySqlDriver' => __DIR__ . '/../../..' . '/system/Database/Drivers/MySqlDriver.php',
        'Luminova\\Database\\Drivers\\PdoDriver' => __DIR__ . '/../../..' . '/system/Database/Drivers/PdoDriver.php',
        'Luminova\\Database\\Query' => __DIR__ . '/../../..' . '/system/Database/Query.php',
        'Luminova\\Email\\Mailer' => __DIR__ . '/../../..' . '/system/Email/Mailer.php',
        'Luminova\\Errors\\Codes' => __DIR__ . '/../../..' . '/system/Errors/Codes.php',
        'Luminova\\Exceptions\\AppException' => __DIR__ . '/../../..' . '/system/Exceptions/AppException.php',
        'Luminova\\Exceptions\\ClassException' => __DIR__ . '/../../..' . '/system/Exceptions/ClassException.php',
        'Luminova\\Exceptions\\DatabaseException' => __DIR__ . '/../../..' . '/system/Exceptions/DatabaseException.php',
        'Luminova\\Exceptions\\ErrorException' => __DIR__ . '/../../..' . '/system/Exceptions/ErrorException.php',
        'Luminova\\Exceptions\\FileException' => __DIR__ . '/../../..' . '/system/Exceptions/FileException.php',
        'Luminova\\Exceptions\\InvalidException' => __DIR__ . '/../../..' . '/system/Exceptions/InvalidException.php',
        'Luminova\\Exceptions\\InvalidObjectException' => __DIR__ . '/../../..' . '/system/Exceptions/InvalidObjectException.php',
        'Luminova\\Exceptions\\LuminovaException' => __DIR__ . '/../../..' . '/system/Exceptions/LuminovaException.php',
        'Luminova\\Exceptions\\NotFoundException' => __DIR__ . '/../../..' . '/system/Exceptions/NotFoundException.php',
        'Luminova\\Exceptions\\RuntimeException' => __DIR__ . '/../../..' . '/system/Exceptions/RuntimeException.php',
        'Luminova\\Exceptions\\ValidationException' => __DIR__ . '/../../..' . '/system/Exceptions/ValidationException.php',
        'Luminova\\Exceptions\\ViewNotFoundException' => __DIR__ . '/../../..' . '/system/Exceptions/ViewNotFoundException.php',
        'Luminova\\Functions\\Functions' => __DIR__ . '/../../..' . '/system/Functions/Functions.php',
        'Luminova\\Http\\AsyncClientInterface' => __DIR__ . '/../../..' . '/system/Http/AsyncClientInterface.php',
        'Luminova\\Http\\Client\\Curl' => __DIR__ . '/../../..' . '/system/Http/Client/Curl.php',
        'Luminova\\Http\\Client\\Guzzle' => __DIR__ . '/../../..' . '/system/Http/Client/Guzzle.php',
        'Luminova\\Http\\CurlAsyncClient' => __DIR__ . '/../../..' . '/system/Http/CurlAsyncClient.php',
        'Luminova\\Http\\GuzzleAsyncClient' => __DIR__ . '/../../..' . '/system/Http/GuzzleAsyncClient.php',
        'Luminova\\Http\\Header' => __DIR__ . '/../../..' . '/system/Http/Header.php',
        'Luminova\\Http\\Network' => __DIR__ . '/../../..' . '/system/Http/Network.php',
        'Luminova\\Http\\NetworkAsync' => __DIR__ . '/../../..' . '/system/Http/NetworkAsync.php',
        'Luminova\\Http\\NetworkClientInterface' => __DIR__ . '/../../..' . '/system/Http/NetworkClientInterface.php',
        'Luminova\\Http\\NetworkRequest' => __DIR__ . '/../../..' . '/system/Http/NetworkRequest.php',
        'Luminova\\Http\\NetworkResponse' => __DIR__ . '/../../..' . '/system/Http/NetworkResponse.php',
        'Luminova\\Http\\Request' => __DIR__ . '/../../..' . '/system/Http/Request.php',
        'Luminova\\Languages\\Translator' => __DIR__ . '/../../..' . '/system/Languages/Translator.php',
        'Luminova\\Logger\\Logger' => __DIR__ . '/../../..' . '/system/Logger/Logger.php',
        'Luminova\\Logger\\LoggerAware' => __DIR__ . '/../../..' . '/system/Logger/LoggerAware.php',
        'Luminova\\Logger\\LoggerInterface' => __DIR__ . '/../../..' . '/system/Logger/LoggerInterface.php',
        'Luminova\\Models\\Model' => __DIR__ . '/../../..' . '/system/Models/Model.php',
        'Luminova\\Models\\PushMessage' => __DIR__ . '/../../..' . '/system/Models/PushMessage.php',
        'Luminova\\Notifications\\FirebasePusher' => __DIR__ . '/../../..' . '/system/Notifications/FirebasePusher.php',
        'Luminova\\Notifications\\FirebaseRealtime' => __DIR__ . '/../../..' . '/system/Notifications/FirebaseRealtime.php',
        'Luminova\\Routing\\Bootstrap' => __DIR__ . '/../../..' . '/system/Routing/Bootstrap.php',
        'Luminova\\Routing\\Router' => __DIR__ . '/../../..' . '/system/Routing/Router.php',
        'Luminova\\Security\\Csrf' => __DIR__ . '/../../..' . '/system/Security/Csrf.php',
        'Luminova\\Security\\Encryption\\AES' => __DIR__ . '/../../..' . '/system/Security/Encryption/AES.php',
        'Luminova\\Security\\Encryption\\EncryptionInterface' => __DIR__ . '/../../..' . '/system/Security/Encryption/EncryptionInterface.php',
        'Luminova\\Security\\InputValidator' => __DIR__ . '/../../..' . '/system/Security/InputValidator.php',
        'Luminova\\Security\\ValidatorInterface' => __DIR__ . '/../../..' . '/system/Security/ValidatorInterface.php',
        'Luminova\\Seo\\Meta' => __DIR__ . '/../../..' . '/system/Seo/Meta.php',
        'Luminova\\Sessions\\CookieManager' => __DIR__ . '/../../..' . '/system/Sessions/CookieManager.php',
        'Luminova\\Sessions\\Session' => __DIR__ . '/../../..' . '/system/Sessions/Session.php',
        'Luminova\\Sessions\\SessionInterface' => __DIR__ . '/../../..' . '/system/Sessions/SessionInterface.php',
        'Luminova\\Sessions\\SessionManager' => __DIR__ . '/../../..' . '/system/Sessions/SessionManager.php',
        'Luminova\\Template\\Template' => __DIR__ . '/../../..' . '/system/Template/Template.php',
        'Luminova\\Time\\Task' => __DIR__ . '/../../..' . '/system/Time/Task.php',
        'Luminova\\Utils\\Queue' => __DIR__ . '/../../..' . '/system/Utils/Queue.php',
        'Psr\\Log\\AbstractLogger' => __DIR__ . '/..' . '/psr/log/Psr/Log/AbstractLogger.php',
        'Psr\\Log\\InvalidArgumentException' => __DIR__ . '/..' . '/psr/log/Psr/Log/InvalidArgumentException.php',
        'Psr\\Log\\LogLevel' => __DIR__ . '/..' . '/psr/log/Psr/Log/LogLevel.php',
        'Psr\\Log\\LoggerAwareInterface' => __DIR__ . '/..' . '/psr/log/Psr/Log/LoggerAwareInterface.php',
        'Psr\\Log\\LoggerAwareTrait' => __DIR__ . '/..' . '/psr/log/Psr/Log/LoggerAwareTrait.php',
        'Psr\\Log\\LoggerInterface' => __DIR__ . '/..' . '/psr/log/Psr/Log/LoggerInterface.php',
        'Psr\\Log\\LoggerTrait' => __DIR__ . '/..' . '/psr/log/Psr/Log/LoggerTrait.php',
        'Psr\\Log\\NullLogger' => __DIR__ . '/..' . '/psr/log/Psr/Log/NullLogger.php',
        'Psr\\Log\\Test\\DummyTest' => __DIR__ . '/..' . '/psr/log/Psr/Log/Test/DummyTest.php',
        'Psr\\Log\\Test\\LoggerInterfaceTest' => __DIR__ . '/..' . '/psr/log/Psr/Log/Test/LoggerInterfaceTest.php',
        'Psr\\Log\\Test\\TestLogger' => __DIR__ . '/..' . '/psr/log/Psr/Log/Test/TestLogger.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit9c155849e043191fc1df7e0b46712cd7::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit9c155849e043191fc1df7e0b46712cd7::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit9c155849e043191fc1df7e0b46712cd7::$classMap;

        }, null, ClassLoader::class);
    }
}
