<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit9c155849e043191fc1df7e0b46712cd7
{
    public static $prefixLengthsPsr4 = array (
        'P' => 
        array (
            'Psr\\Log\\' => 8,
            'PHPMailer\\PHPMailer\\' => 20,
        ),
        'L' => 
        array (
            'Luminova\\Time\\' => 14,
            'Luminova\\Template\\' => 18,
            'Luminova\\Storage\\' => 17,
            'Luminova\\Sessions\\' => 18,
            'Luminova\\Seo\\' => 13,
            'Luminova\\Security\\Encryption\\' => 29,
            'Luminova\\Security\\' => 18,
            'Luminova\\Routing\\' => 16,
            'Luminova\\Notifications\\' => 23,
            'Luminova\\Models\\' => 16,
            'Luminova\\Logger\\' => 16,
            'Luminova\\Languages\\' => 19,
            'Luminova\\Http\\' => 14,
            'Luminova\\Functions\\' => 19,
            'Luminova\\Exceptions\\' => 20,
            'Luminova\\Errors\\' => 16,
            'Luminova\\Database\\Drivers\\' => 26,
            'Luminova\\Database\\' => 18,
            'Luminova\\Config\\' => 16,
            'Luminova\\Composer\\' => 18,
            'Luminova\\Command\\' => 17,
            'Luminova\\Cache\\' => 15,
            'Luminova\\Arrays\\' => 16,
            'Luminova\\' => 9,
        ),
        'A' => 
        array (
            'App\\Controllers\\Models\\' => 23,
            'App\\Controllers\\Config\\' => 23,
            'App\\Controllers\\' => 16,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Psr\\Log\\' => 
        array (
            0 => __DIR__ . '/..' . '/psr/log/Psr/Log',
        ),
        'PHPMailer\\PHPMailer\\' => 
        array (
            0 => __DIR__ . '/..' . '/phpmailer/phpmailer/src',
        ),
        'Luminova\\Time\\' => 
        array (
            0 => __DIR__ . '/../../..' . '/system/Time',
        ),
        'Luminova\\Template\\' => 
        array (
            0 => __DIR__ . '/../../..' . '/system/Template',
        ),
        'Luminova\\Storage\\' => 
        array (
            0 => __DIR__ . '/../../..' . '/system/Storage',
        ),
        'Luminova\\Sessions\\' => 
        array (
            0 => __DIR__ . '/../../..' . '/system/Sessions',
        ),
        'Luminova\\Seo\\' => 
        array (
            0 => __DIR__ . '/../../..' . '/system/Seo',
        ),
        'Luminova\\Security\\Encryption\\' => 
        array (
            0 => __DIR__ . '/../../..' . '/system/Security/Encryption',
        ),
        'Luminova\\Security\\' => 
        array (
            0 => __DIR__ . '/../../..' . '/system/Security',
        ),
        'Luminova\\Routing\\' => 
        array (
            0 => __DIR__ . '/../../..' . '/system/Routing',
        ),
        'Luminova\\Notifications\\' => 
        array (
            0 => __DIR__ . '/../../..' . '/system/Notifications',
        ),
        'Luminova\\Models\\' => 
        array (
            0 => __DIR__ . '/../../..' . '/system/Models',
        ),
        'Luminova\\Logger\\' => 
        array (
            0 => __DIR__ . '/../../..' . '/system/Logger',
        ),
        'Luminova\\Languages\\' => 
        array (
            0 => __DIR__ . '/../../..' . '/system/Languages',
        ),
        'Luminova\\Http\\' => 
        array (
            0 => __DIR__ . '/../../..' . '/system/Http',
        ),
        'Luminova\\Functions\\' => 
        array (
            0 => __DIR__ . '/../../..' . '/system/Functions',
        ),
        'Luminova\\Exceptions\\' => 
        array (
            0 => __DIR__ . '/../../..' . '/system/Exceptions',
        ),
        'Luminova\\Errors\\' => 
        array (
            0 => __DIR__ . '/../../..' . '/system/Errors',
        ),
        'Luminova\\Database\\Drivers\\' => 
        array (
            0 => __DIR__ . '/../../..' . '/system/Database/Drivers',
        ),
        'Luminova\\Database\\' => 
        array (
            0 => __DIR__ . '/../../..' . '/system/Database',
        ),
        'Luminova\\Config\\' => 
        array (
            0 => __DIR__ . '/../../..' . '/system/Config',
        ),
        'Luminova\\Composer\\' => 
        array (
            0 => __DIR__ . '/../../..' . '/system/Composer',
        ),
        'Luminova\\Command\\' => 
        array (
            0 => __DIR__ . '/../../..' . '/system/Command',
        ),
        'Luminova\\Cache\\' => 
        array (
            0 => __DIR__ . '/../../..' . '/system/Cache',
        ),
        'Luminova\\Arrays\\' => 
        array (
            0 => __DIR__ . '/../../..' . '/system/Arrays',
        ),
        'Luminova\\' => 
        array (
            0 => __DIR__ . '/../../..' . '/system',
        ),
        'App\\Controllers\\Models\\' => 
        array (
            0 => __DIR__ . '/../../..' . '/app/Controllers/Models',
        ),
        'App\\Controllers\\Config\\' => 
        array (
            0 => __DIR__ . '/../../..' . '/app/Controllers/Config',
        ),
        'App\\Controllers\\' => 
        array (
            0 => __DIR__ . '/../../..' . '/app/Controllers',
        ),
    );

    public static $classMap = array (
        'App\\Controllers\\AppSession' => __DIR__ . '/../../..' . '/app/Controllers/AppSession.php',
        'App\\Controllers\\Application' => __DIR__ . '/../../..' . '/app/Controllers/Application.php',
        'App\\Controllers\\Config\\Config' => __DIR__ . '/../../..' . '/app/Controllers/Config/Config.php',
        'App\\Controllers\\Config\\SessionConfig' => __DIR__ . '/../../..' . '/app/Controllers/Config/SessionConfig.php',
        'App\\Controllers\\EmailTemplate' => __DIR__ . '/../../..' . '/app/Controllers/EmailTemplate.php',
        'App\\Controllers\\Func' => __DIR__ . '/../../..' . '/app/Controllers/Func.php',
        'App\\Controllers\\HelloWorld' => __DIR__ . '/../../..' . '/app/Controllers/HelloWorld.php',
        'App\\Controllers\\Models\\UserModel' => __DIR__ . '/../../..' . '/app/Controllers/Models/UserModel.php',
        'App\\Controllers\\UserController' => __DIR__ . '/../../..' . '/app/Controllers/UserController.php',
        'App\\Controllers\\UserModel' => __DIR__ . '/../../..' . '/app/Controllers/UserModel.php',
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
        'Luminova\\Arrays\\ArrayInput' => __DIR__ . '/../../..' . '/system/Arrays/ArrayInput.php',
        'Luminova\\BaseApplication' => __DIR__ . '/../../..' . '/system/BaseApplication.php',
        'Luminova\\BaseController' => __DIR__ . '/../../..' . '/system/BaseController.php',
        'Luminova\\Cache\\Cache' => __DIR__ . '/../../..' . '/system/Cache/Cache.php',
        'Luminova\\Cache\\Compress' => __DIR__ . '/../../..' . '/system/Cache/Compress.php',
        'Luminova\\Cache\\FileCacheItem' => __DIR__ . '/../../..' . '/system/Cache/FileCacheItem.php',
        'Luminova\\Cache\\FileSystemCache' => __DIR__ . '/../../..' . '/system/Cache/FileSystemCache.php',
        'Luminova\\Cache\\MemoryCache' => __DIR__ . '/../../..' . '/system/Cache/MemoryCache.php',
        'Luminova\\Cache\\Optimizer' => __DIR__ . '/../../..' . '/system/Cache/Optimizer.php',
        'Luminova\\Command\\AppCommand' => __DIR__ . '/../../..' . '/system/Command/AppCommand.php',
        'Luminova\\Command\\Create' => __DIR__ . '/../../..' . '/system/Command/Create.php',
        'Luminova\\Command\\Plugin' => __DIR__ . '/../../..' . '/system/Command/Plugin.php',
        'Luminova\\Command\\RebuildCommand' => __DIR__ . '/../../..' . '/system/Command/RebuildCommand.php',
        'Luminova\\Command\\Subscriber' => __DIR__ . '/../../..' . '/system/Command/Subscriber.php',
        'Luminova\\Composer\\BaseComposer' => __DIR__ . '/../../..' . '/system/Composer/BaseComposer.php',
        'Luminova\\Composer\\Builder' => __DIR__ . '/../../..' . '/system/Composer/Builder.php',
        'Luminova\\Composer\\Updater' => __DIR__ . '/../../..' . '/system/Composer/Updater.php',
        'Luminova\\Config\\BaseConfig' => __DIR__ . '/../../..' . '/system/Config/BaseConfig.php',
        'Luminova\\Config\\DotEnv' => __DIR__ . '/../../..' . '/system/Config/DotEnv.php',
        'Luminova\\Config\\PHPStanRules' => __DIR__ . '/../../..' . '/system/Config/PHPStanRules.php',
        'Luminova\\Database\\Columns' => __DIR__ . '/../../..' . '/system/Database/Columns.php',
        'Luminova\\Database\\Conn' => __DIR__ . '/../../..' . '/system/Database/Conn.php',
        'Luminova\\Database\\DatabaseInterface' => __DIR__ . '/../../..' . '/system/Database/DatabaseInterface.php',
        'Luminova\\Database\\Drivers\\MySqlDriver' => __DIR__ . '/../../..' . '/system/Database/Drivers/MySqlDriver.php',
        'Luminova\\Database\\Drivers\\PdoDriver' => __DIR__ . '/../../..' . '/system/Database/Drivers/PdoDriver.php',
        'Luminova\\Database\\Query' => __DIR__ . '/../../..' . '/system/Database/Query.php',
        'Luminova\\Email\\Mailer' => __DIR__ . '/../../..' . '/system/Email/Mailer.php',
        'Luminova\\Errors\\Codes' => __DIR__ . '/../../..' . '/system/Errors/Codes.php',
        'Luminova\\Exceptions\\AppException' => __DIR__ . '/../../..' . '/system/Exceptions/AppException.php',
        'Luminova\\Exceptions\\ClassException' => __DIR__ . '/../../..' . '/system/Exceptions/ClassException.php',
        'Luminova\\Exceptions\\DatabaseException' => __DIR__ . '/../../..' . '/system/Exceptions/DatabaseException.php',
        'Luminova\\Exceptions\\ErrorException' => __DIR__ . '/../../..' . '/system/Exceptions/ErrorException.php',
        'Luminova\\Exceptions\\FileException' => __DIR__ . '/../../..' . '/system/Exceptions/FileException.php',
        'Luminova\\Exceptions\\InvalidException' => __DIR__ . '/../../..' . '/system/Exceptions/InvalidException.php',
        'Luminova\\Exceptions\\InvalidObjectException' => __DIR__ . '/../../..' . '/system/Exceptions/InvalidObjectException.php',
        'Luminova\\Exceptions\\LuminovaException' => __DIR__ . '/../../..' . '/system/Exceptions/LuminovaException.php',
        'Luminova\\Exceptions\\NotFoundException' => __DIR__ . '/../../..' . '/system/Exceptions/NotFoundException.php',
        'Luminova\\Exceptions\\ValidationException' => __DIR__ . '/../../..' . '/system/Exceptions/ValidationException.php',
        'Luminova\\Exceptions\\ViewNotFoundException' => __DIR__ . '/../../..' . '/system/Exceptions/ViewNotFoundException.php',
        'Luminova\\Functions\\FunctionInterface' => __DIR__ . '/../../..' . '/system/Functions/FunctionInterface.php',
        'Luminova\\Functions\\Functions' => __DIR__ . '/../../..' . '/system/Functions/Functions.php',
        'Luminova\\Http\\AsyncClientInterface' => __DIR__ . '/../../..' . '/system/Http/AsyncClientInterface.php',
        'Luminova\\Http\\CurlAsyncClient' => __DIR__ . '/../../..' . '/system/Http/CurlAsyncClient.php',
        'Luminova\\Http\\CurlClient' => __DIR__ . '/../../..' . '/system/Http/CurlClient.php',
        'Luminova\\Http\\CurlResponse' => __DIR__ . '/../../..' . '/system/Http/CurlResponse.php',
        'Luminova\\Http\\GuzzleAsyncClient' => __DIR__ . '/../../..' . '/system/Http/GuzzleAsyncClient.php',
        'Luminova\\Http\\GuzzleClient' => __DIR__ . '/../../..' . '/system/Http/GuzzleClient.php',
        'Luminova\\Http\\Header' => __DIR__ . '/../../..' . '/system/Http/Header.php',
        'Luminova\\Http\\Network' => __DIR__ . '/../../..' . '/system/Http/Network.php',
        'Luminova\\Http\\NetworkAsync' => __DIR__ . '/../../..' . '/system/Http/NetworkAsync.php',
        'Luminova\\Http\\NetworkRequest' => __DIR__ . '/../../..' . '/system/Http/NetworkRequest.php',
        'Luminova\\Http\\Request' => __DIR__ . '/../../..' . '/system/Http/Request.php',
        'Luminova\\Languages\\Translator' => __DIR__ . '/../../..' . '/system/Languages/Translator.php',
        'Luminova\\Logger\\Logger' => __DIR__ . '/../../..' . '/system/Logger/Logger.php',
        'Luminova\\Logger\\LoggerAware' => __DIR__ . '/../../..' . '/system/Logger/LoggerAware.php',
        'Luminova\\Logger\\LoggerInterface' => __DIR__ . '/../../..' . '/system/Logger/LoggerInterface.php',
        'Luminova\\Models\\DatabaseConfig' => __DIR__ . '/../../..' . '/system/Models/DatabaseConfig.php',
        'Luminova\\Models\\Model' => __DIR__ . '/../../..' . '/system/Models/Model.php',
        'Luminova\\Models\\PushMessage' => __DIR__ . '/../../..' . '/system/Models/PushMessage.php',
        'Luminova\\Notifications\\FirebasePusher' => __DIR__ . '/../../..' . '/system/Notifications/FirebasePusher.php',
        'Luminova\\Notifications\\FirebaseRealtime' => __DIR__ . '/../../..' . '/system/Notifications/FirebaseRealtime.php',
        'Luminova\\Routing\\Router' => __DIR__ . '/../../..' . '/system/Routing/Router.php',
        'Luminova\\Security\\Csrf' => __DIR__ . '/../../..' . '/system/Security/Csrf.php',
        'Luminova\\Security\\Encryption\\AES' => __DIR__ . '/../../..' . '/system/Security/Encryption/AES.php',
        'Luminova\\Security\\Encryption\\EncryptionInterface' => __DIR__ . '/../../..' . '/system/Security/Encryption/EncryptionInterface.php',
        'Luminova\\Security\\InputValidator' => __DIR__ . '/../../..' . '/system/Security/InputValidator.php',
        'Luminova\\Security\\ValidatorInterface' => __DIR__ . '/../../..' . '/system/Security/ValidatorInterface.php',
        'Luminova\\Seo\\Meta' => __DIR__ . '/../../..' . '/system/Seo/Meta.php',
        'Luminova\\Sessions\\CookieManager' => __DIR__ . '/../../..' . '/system/Sessions/CookieManager.php',
        'Luminova\\Sessions\\Session' => __DIR__ . '/../../..' . '/system/Sessions/Session.php',
        'Luminova\\Sessions\\SessionInterface' => __DIR__ . '/../../..' . '/system/Sessions/SessionInterface.php',
        'Luminova\\Sessions\\SessionManager' => __DIR__ . '/../../..' . '/system/Sessions/SessionManager.php',
        'Luminova\\Template\\Template' => __DIR__ . '/../../..' . '/system/Template/Template.php',
        'Luminova\\Time\\Task' => __DIR__ . '/../../..' . '/system/Time/Task.php',
        'PHPMailer\\PHPMailer\\DSNConfigurator' => __DIR__ . '/..' . '/phpmailer/phpmailer/src/DSNConfigurator.php',
        'PHPMailer\\PHPMailer\\Exception' => __DIR__ . '/..' . '/phpmailer/phpmailer/src/Exception.php',
        'PHPMailer\\PHPMailer\\OAuth' => __DIR__ . '/..' . '/phpmailer/phpmailer/src/OAuth.php',
        'PHPMailer\\PHPMailer\\OAuthTokenProvider' => __DIR__ . '/..' . '/phpmailer/phpmailer/src/OAuthTokenProvider.php',
        'PHPMailer\\PHPMailer\\PHPMailer' => __DIR__ . '/..' . '/phpmailer/phpmailer/src/PHPMailer.php',
        'PHPMailer\\PHPMailer\\POP3' => __DIR__ . '/..' . '/phpmailer/phpmailer/src/POP3.php',
        'PHPMailer\\PHPMailer\\SMTP' => __DIR__ . '/..' . '/phpmailer/phpmailer/src/SMTP.php',
        'Psr\\Log\\AbstractLogger' => __DIR__ . '/..' . '/psr/log/Psr/Log/AbstractLogger.php',
        'Psr\\Log\\InvalidArgumentException' => __DIR__ . '/..' . '/psr/log/Psr/Log/InvalidArgumentException.php',
        'Psr\\Log\\LogLevel' => __DIR__ . '/..' . '/psr/log/Psr/Log/LogLevel.php',
        'Psr\\Log\\LoggerAwareInterface' => __DIR__ . '/..' . '/psr/log/Psr/Log/LoggerAwareInterface.php',
        'Psr\\Log\\LoggerAwareTrait' => __DIR__ . '/..' . '/psr/log/Psr/Log/LoggerAwareTrait.php',
        'Psr\\Log\\LoggerInterface' => __DIR__ . '/..' . '/psr/log/Psr/Log/LoggerInterface.php',
        'Psr\\Log\\LoggerTrait' => __DIR__ . '/..' . '/psr/log/Psr/Log/LoggerTrait.php',
        'Psr\\Log\\NullLogger' => __DIR__ . '/..' . '/psr/log/Psr/Log/NullLogger.php',
        'Psr\\Log\\Test\\DummyTest' => __DIR__ . '/..' . '/psr/log/Psr/Log/Test/DummyTest.php',
        'Psr\\Log\\Test\\LoggerInterfaceTest' => __DIR__ . '/..' . '/psr/log/Psr/Log/Test/LoggerInterfaceTest.php',
        'Psr\\Log\\Test\\TestLogger' => __DIR__ . '/..' . '/psr/log/Psr/Log/Test/TestLogger.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit9c155849e043191fc1df7e0b46712cd7::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit9c155849e043191fc1df7e0b46712cd7::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit9c155849e043191fc1df7e0b46712cd7::$classMap;

        }, null, ClassLoader::class);
    }
}
